### ISSUE TITLE
Don't have the localization

### ISSUE THREAD

**Issue by MightyCreak** [CNRS-DSI-Dev/dashboard#13]
Hi!

I removed the "apps/dashboard" directory, that I downloaded from the [ownCloud app store](https://apps.owncloud.com/content/show.php/Dashboard?content=167139), to replace it by the [git release v1.2](https://github.com/CNRS-DSI-Dev/dashboard/releases/tag/v1.2) (because the version number in appinfo.xml is wrong in the app store release).

And I don't know why, but now I don't have the French localization anymore... Despite the fact that the French localization files are here:

```
$ grep "Disk space" -r dashboard-1.2
dashboard-1.2/templates/main.php:    <p class="header"><?php p($l->t('Disk space')); ?> <span>{{ stats.history.totalUsedSpace | humanFileSize }}</span></p>
Binary file dashboard-1.2/l10n/fr/dashboard.mo matches
dashboard-1.2/l10n/fr/dashboard.po:msgid "Disk space"
dashboard-1.2/l10n/fr.php:"Disk space" => "Espace disque",
```

How is the language selected during the install process?

**Comment by ppaysant** [comment]
Hello @MightyCreak 

The ownCloud default language is english, which you can change in config.php (
```php
'default_language' => 'fr',
```

Or you can select a lnaguage once you're connected in your personnal settings page (url `index.php/settings/personal`).

Hope this help,
Best regards

**Comment by MightyCreak** [comment]
My language was already in French, but in doubt I changed it back to English and then French again, but the Dashboard is still in English.

Then I added `'default_language' => 'fr',` in config.php, but Dashboard is still in English.

**Comment by ppaysant** [comment]
Hello @MightyCreak 

I'm unable to reproduce your problem on my different install.
Is your other apps correctly translated (in other terms, is the dashboard app the only one to have translation problem, or not) ?
Are the system rights correct on files (are they readable by your web server) ?
Do you have a php cache wrapper that may interfere ?
Can you give me some iformations on your install (operating system, owncloud version, web server version, php version) ?

I do not see any reason to your problem butI hope your answers will bring some light.

Best regards,

**Comment by MightyCreak** [comment]
> Is your other apps correctly translated (in other terms, is the dashboard app the only one to have translation problem, or not) ?

All my other official apps are correctly in French. But I've just discovered that my hand-installed Music app might have the same problem as Dashboard...

> Are the system rights correct on files (are they readable by your web server) ?

For the rights, I got most of the apps in `root:root` except for calendar, contacts and documents which are `www-data:www-data`. All are 755 for dirs or 644 for files. I've seen no help about the right way of installing an app, I simply copy/paste the app directory into my `apps` directory.

Which app should be root and which app should be www-data?

> Do you have a php cache wrapper that may interfere ?

I don't know how to see that...

> Can you give me some iformations on your install (operating system, owncloud version, web server version, php version) ?

It's a Debian 7, with a recently updated ownCloud 8, on an Nginx/1.2.1 web server, with PHP 5.4.

Thanks!

**Comment by ppaysant** [comment]
If your server may access the files (www-data readable), it should be ok.

Maybe you can have a look on your owncloud log, just in case you may see specific entries about translations.

There may be a problem in the way you hand-install your apps, as Music has problem too. You may verify again, and precisely, if the l10n directory and files inside are readable for www-data.

Best regards,

**Comment by MightyCreak** [comment]
I might have missed this step in the [documentation](http://doc.owncloud.org/server/8.0/admin_manual/installation/apps_management_installation.html#adding-third-party-apps):

> 5. Ensure the permissions and ownership are similar to the other ownCloud apps. Typically, access rights are rwxr-x—, or 0750 in octal notation, and the owner and group are your HTTP user. On CentOS this is apache, Ubuntu is www-data, and on openSUSE is it wwwrun:www.

It's not clear about the "other apps" since among official apps, some are root and some are www-data. But well, since it doesn't work with root, I'll try with www-data!

**Comment by MightyCreak** [comment]
I set the www-data user and group for the whole `dashboard` directory (recursively), but it still doesn't work.

**Comment by ppaysant** [comment]
Hello @MightyCreak 

Did you have a look on the owncloud log ?

**Comment by MightyCreak** [comment]
I disabled the Music app (which apparently spammed my log) and when I refresh the Dashboard page I only get this in the log:

    Error 	PHP 	Undefined index: defaultValue at /var/www/owncloud/core/ajax/appconfig.php#30 	2015-02-16T14:00:02+00:00

Tested 3 times, each time I refresh the Dashboard, I got this error. Not sure it's related to l10n though.

That being said, I installed Tasks recently and the localization works fine there, so it seems to be a problem I have with some 3rd party apps, not all of them.

**Comment by ppaysant** [comment]
Hello @MightyCreak 

Sorry, I've no more idea for your pb.
I will probably work on dashboard to get it usable in OC8, maybe I will find something that relate to this bug.

Best regards,

**Comment by MightyCreak** [comment]
No worries. I'm pretty sure I had Dashboard localization working on OC7, so maybe something has changed on OC8... We'll see!

**Comment by ppaysant** [comment]
@MightyCreak 

I just realized that you said you're using OC8 !!! I do not have work on OC8 compatibility for now, so it's probably the source of your problem. 
I hope to be able to work on dahboard for OC8 in next weeks, I will have a close look on that l10n bug.

Best regards
