### ISSUE TITLE
simple box with editable plain text (or html), at least from a file or a static text for all users

### ISSUE THREAD

**Issue by mckaygerhard** [CNRS-DSI-Dev/dashboard#14]
hi @ppaysant this are a interesting app.. 

please guide me how can i made of if u can made and box with some text feated, or better how can i added two boxeds

for now, not per users, a simple plain text that will be visible for all users! i really need this for made the oc deploy a intranet in all.. 

this app are promised in future can made the oc a complete intranet for enterprises..

**Comment by ppaysant** [comment]
Hello @mckaygerhard 

This app won't be a portal, it just gets and displays some stats on owncloud use. So chances are that this type of feature won't be implemented.
There are other apps that are more interesting as for portal implementation, like https://apps.owncloud.com/content/show.php/dashboard?content=160265

Best regards,

**Comment by mckaygerhard** [comment]
i not talk about a portal,  i talk about an intranet, a inside portal only for employers or alumns inside a local/mapped network of enterprices or a institute..

well, ok, i got it! but i issue that request due the other app are mysql focused and breaks all the sql standars.. i used super scalar deploys in my network enterprise... seem similar on CNRS.. 

i see that, i can see the other apps that are under the path, are focused on usage on the CNRS.. very good, the theming apply many firms but without modify the oc sources.. good idea..

but please, think about it! i have varius oc deployed in my intranet (Venezuela, Panama) for my job issues.. oc with some plugins can be a good intranet! like the google apps suite that is commercial!
