### ISSUE TITLE
dashboard id already used by annother app, this are not a dashboard, its "usage related"

### ISSUE THREAD

**Issue by mckaygerhard** [CNRS-DSI-Dev/dashboard#16]
this app have the same id of this one: https://github.com/CNRS-DSI-Dev/dashboard/

but the other only display statics usage, and this app display more usefully witgets..

i think this app must change the name due a real "dasboard" not only display only "usage statis"

this are not a dashboard, its "usage related"

see: https://github.com/fjies/dashboard/issues/113

**Comment by ppaysant** [comment]
Second link does not answer any more. I close the issue
