### ISSUE TITLE
error getting stats accesss

### ISSUE THREAD

**Issue by mckaygerhard** [CNRS-DSI-Dev/dashboard#28]
either using stable 7 brand or lasted commits i got this error:

```
GET http://mydomain.domain/owncloud/index.php/apps/dashboad/api/1.0/history_stats/json/none/nbUsers/30/1 
500 (Internal Server Error)
```

and also some debug in chrome get authentication error rely on security issues, some tips why this happened?

**Comment by ppaysant** [comment]
Hello,

Can you please give OC and PHP version ?
If possible, attach error stack could be usefull also.

Regards

**Comment by mckaygerhard** [comment]
OC 7 PHP 5.3, this are not relevant, due today i installed 
OC 8 and php 5.4 and give me same error

the web server are lighttpd this are relevant and could influence, i used lighty due are superior in performance, due i have a huge amount of users (7000 around) and use large scalar DB (postgres) due the trafic are huge very huge (theres a problem in performance if use mysql for huge amount of files when those are smaller and there's many sync between clients and server with the oc client)

the network trace in chrome said:
> XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check 

and in the stack network time have:
> CORS requires basic auth

the owncloudlog does not show any related log error, only the browser:

```
GET http://midominio/owncloud/index.php/apps/dashboard/api/1.0/history_stats/json/none/nbUsers/30/1 
500 (Internal Server Error)
(anonymous) @ angular.min.js?v=aea2467…:79
s @ angular.min.js?v=aea2467…:74
f @ angular.min.js?v=aea2467…:71
L @ angular.min.js?v=aea2467…:100
L @ angular.min.js?v=aea2467…:100
(anonymous) @ angular.min.js?v=aea2467…:101
$eval @ angular.min.js?v=aea2467…:112
$digest @ angular.min.js?v=aea2467…:109
$apply @ angular.min.js?v=aea2467…:112
(anonymous) @ angular.min.js?v=aea2467…:18
d @ angular.min.js?v=aea2467…:35
c @ angular.min.js?v=aea2467…:18
fc @ angular.min.js?v=aea2467…:18
Xc @ angular.min.js?v=aea2467…:17
(anonymous) @ angular.min.js?v=aea2467…:214
c @ jquery-1.10.0.min.js?v=aea2467…:4
fireWith @ jquery-1.10.0.min.js?v=aea2467…:4
ready @ jquery-1.10.0.min.js?v=aea2467…:4
q @ jquery-1.10.0.min.js?v=aea2467…:4
angular.min.js?v=aea2467…:79GET http://midominio/owncloud/index.php/apps/dashboard/api/1.0/index.json 500 (Internal Server Error)
(anonymous) @ angular.min.js?v=aea2467…:79
s @ angular.min.js?v=aea2467…:74
f @ angular.min.js?v=aea2467…:71
L @ angular.min.js?v=aea2467…:100
L @ angular.min.js?v=aea2467…:100
(anonymous) @ angular.min.js?v=aea2467…:101
$eval @ angular.min.js?v=aea2467…:112
$digest @ angular.min.js?v=aea2467…:109
$apply @ angular.min.js?v=aea2467…:112
(anonymous) @ angular.min.js?v=aea2467…:18
d @ angular.min.js?v=aea2467…:35
c @ angular.min.js?v=aea2467…:18
fc @ angular.min.js?v=aea2467…:18
Xc @ angular.min.js?v=aea2467…:17
(anonymous) @ angular.min.js?v=aea2467…:214
c @ jquery-1.10.0.min.js?v=aea2467…:4
fireWith @ jquery-1.10.0.min.js?v=aea2467…:4
ready @ jquery-1.10.0.min.js?v=aea2467…:4
q @ jquery-1.10.0.min.js?v=aea2467…:4
angular.min.js?v=aea2467…:79GET http://midominio/owncloud/index.php/apps/dashboard/api/1.0/stats_enabled_groups 401 (Unauthorized)
(anonymous) @ angular.min.js?v=aea2467…:79
s @ angular.min.js?v=aea2467…:74
f @ angular.min.js?v=aea2467…:71
L @ angular.min.js?v=aea2467…:100
L @ angular.min.js?v=aea2467…:100
(anonymous) @ angular.min.js?v=aea2467…:101
$eval @ angular.min.js?v=aea2467…:112
$digest @ angular.min.js?v=aea2467…:109
$apply @ angular.min.js?v=aea2467…:112
(anonymous) @ angular.min.js?v=aea2467…:18
d @ angular.min.js?v=aea2467…:35
c @ angular.min.js?v=aea2467…:18
fc @ angular.min.js?v=aea2467…:18
Xc @ angular.min.js?v=aea2467…:17
(anonymous) @ angular.min.js?v=aea2467…:214
c @ jquery-1.10.0.min.js?v=aea2467…:4
fireWith @ jquery-1.10.0.min.js?v=aea2467…:4
ready @ jquery-1.10.0.min.js?v=aea2467…:4
q @ jquery-1.10.0.min.js?v=aea2467…:4
angular.min.js?v=aea2467…:79 GET http://midominio/owncloud/index.php/apps/dashboard/api/1.0/is_groups_enabled 401 (Unauthorized)
```

**Comment by ppaysant** [comment]
Hi @mckaygerhard 

Error 500 means server side error, so the trace that can help me is apache/php log or (more probably) owncloud.log. It is probably verbose, so you may like best attach log extract instead of copy/paste it :)

Anyway, just to be complete, dashboard master branch (release 2.0) is for OC9+ and now OC10 beta, it has not be tested on OC8. And dashboard branch stable7 (release 1.0 to 1.2) has been tested only onOC 7.0.5. Unfortunately I have not enough time to test / debug other OC versions than these.

Regards

**Comment by ejouvin** [comment]
Got the same error 500 just after install.
But, the day after, it works well.

May be an error when there is nothing in tables.

**Comment by mckaygerhard** [comment]
@ejouvin has the same error, and u update and cut me the possibility to still using the app to produce only in the xtremelly slowlly OC 9/10 beta.. vendors still using php 5.3 and 5.4 with patches so "security" its not excuse.. and oc newers are more slower due have more linex to compute..

its clarrelly its not the oc version.. some time before i posted about changes in the code that i think may affect the data.. 
the "dashboard" (that its nothigh similar to dashboard, seems more like a storeboard stast) need some firts shots to make first stats.. but seems that this never hallen and then no data its retrieved from server..

its just a teory..

**Comment by ppaysant** [comment]
@ejouvin, thx for your comment :)

@mckaygerhard 
The error effectly appears when no data is stored in DB. The php script now throws back a 422 error code and the js code displays a specific message. As written in readme, stats are collected via cron once a day.

I close this issue

**Comment by mckaygerhard** [comment]
umm ok i see the commit, u only change the display when no stats are collected, but no data collection related code was commit... 

now i have a doub.. i never see that in all cases in all issues users reports that plugin collect some data...

**Comment by mckaygerhard** [comment]
umm ok i see the commit, u only change the display when no stats are collected, but no data collection related code was commit...

now i have a doub.. i never see that in all cases in all issues users reports that plugin collect some data... as described in issue #22
