### ISSUE TITLE
Displayed values format

### ISSUE THREAD

**Issue by juju95** [CNRS-DSI-Dev/dashboard#3]
I see that you are from france too but i will stay in english ;)

For the graph on the bottom of the page, some cosmetic update could be possible on Y axes values ?  : 
- For used space / size per user / size per folder / Size per file , convert values to Ko, Mo, Go etc ?
  currently i have values like 125000000 130000000 etc. would be better for fast reading ;)
- I know it is an average, but would be cleaner to round files per users, folders per user etc values to integer, to have .25 or .75 values are not really interesting ( or possible config input to choose ? )
- And stranger, if the value of a graph didn't change between the start and the end, instead if a a stable line, we get an empty graph, is it normal ?

And for the futur, could it be possible to have a "per user" dashboard, where he only see his stats, his directory occupation etc. ?

Again a really good and clean app for owncloud users, thanks !

**Comment by ppaysant** [comment]
V2 is out, and the graph component has been changed (no more "empty graph bug"). I close the issue
