### ISSUE TITLE
1.2 Will not Upgrade

### ISSUE THREAD

**Issue by domneu** [CNRS-DSI-Dev/dashboard#9]
I disabled the version 1.1 that I had installed, deleted the "dashboard" directory in apps and copied in the new 1.2 version "dashboard" directory. When I go to its apps admin page, there is an option to enable it and also an option to upgrade it to 1.2 (but this IS the v1.2 app). I click the upgrade button, but it just sits in the updating state. I attempt to do something else and it tells me OC is being updated and to try again later. I eventually have to change the "maintenance=true" to false to get OC back. Any suggestions?

Thank you,
Dominic

**Comment by MightyCreak** [comment]
It would be cool to have a small section under the "Install" one to now what's the good practice to update to a new version. Even if it's the regular way of doing it for an ownCloud app, it would help a lot the newcomers.

**Comment by ppaysant** [comment]
Hello @MightyCreak ,

It is a ownCloud7 bug, the "uninstall" feature does not clean the oc_appconfig, then the app does not know that it has to upgrade or fresh-install.

Maybe you can fill an issue on core repository.

Best regards
